import React, { useState } from 'react';
import { Sparkles, Loader2, Download, Image as ImageIcon, Wand2, RefreshCw } from 'lucide-react';
import { brandApi } from '../../api/brandApi';
import { toast } from 'sonner';
import { motion, AnimatePresence } from 'framer-motion';

export const LogoLab = ({ lang }: { lang: 'ar' | 'en' }) => {
  const [prompt, setPrompt] = useState('');
  const [result, setResult] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [modelUsed, setModelUsed] = useState<string | null>(null);
  const [availableModels, setAvailableModels] = useState<{ id: string, name: string }[]>([]);
  const [selectedModel, setSelectedModel] = useState<string>('');

  React.useEffect(() => {
    brandApi.getModels().then(models => {
      setAvailableModels(models);
      if (models.length > 0) setSelectedModel(models[0].name);
    }).catch(console.error);
  }, []);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setIsLoading(true);
    setResult(null);
    try {
      const res = await brandApi.executeUniversal({
        prompt: `A ultra-premium, minimalist, and unique professional logo for: ${prompt}. The design should be iconic, modern, and high-end. Use a clean white background. Vector style, corporate identity, 4k resolution.`,
        taskType: "vision",
        modelName: selectedModel || undefined
      });
      
      let imageUrl = res.text || res.uri || res;
      if (typeof imageUrl !== 'string' && imageUrl && imageUrl.text) imageUrl = imageUrl.text;
      
      if (imageUrl && typeof imageUrl === 'string') {
        const urlToUse = imageUrl.trim();
        setResult(urlToUse);
        setModelUsed(res.modelUsed || selectedModel || "Unknown");
        toast.success(lang === 'ar' ? `تم توليد الشعار بواسطة ${res.modelUsed || selectedModel || "Unknown"}` : `Logo generated by ${res.modelUsed || selectedModel || "Unknown"}`);
      } else {
        throw new Error("Invalid response format: No image URL returned");
      }
    } catch (e) {
      console.error("Logo generation error:", e);
      toast.error(lang === 'ar' ? 'فشل توليد الشعار، يرجى المحاولة مرة أخرى' : 'Failed to generate logo, please try again');
    } finally {
      setIsLoading(false);
    }
  };

  const suggestions = [
    lang === 'ar' ? 'شركة تقنية ناشئة باسم "نيكسوس"' : 'A tech startup named "Nexus"',
    lang === 'ar' ? 'مطعم فاخر للمأكولات البحرية' : 'A luxury seafood restaurant',
    lang === 'ar' ? 'تطبيق للياقة البدنية والصحة' : 'A fitness and health app',
    lang === 'ar' ? 'وكالة عقارية حديثة' : 'A modern real estate agency'
  ];

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <div className="p-8 bg-zinc-900 border border-zinc-800 rounded-[32px] relative overflow-hidden">
        <div className="absolute top-4 right-4 rtl:left-4 rtl:right-auto z-20">
          <select 
            value={selectedModel} 
            onChange={(e) => setSelectedModel(e.target.value)}
            className="bg-transparent text-purple-500/50 hover:text-purple-500 text-xs p-1 outline-none cursor-pointer"
          >
            <option value="">{lang === 'ar' ? 'نموذج تلقائي' : 'Auto Model'}</option>
            {availableModels.map(model => (
              <option key={model.id} value={model.name}>{model.name}</option>
            ))}
          </select>
        </div>
        <div className="absolute top-0 right-0 p-8 opacity-10">
          <Sparkles className="w-32 h-32 text-purple-500" />
        </div>

        <div className="relative z-10">
          <h2 className="text-3xl font-black mb-2 flex items-center gap-3">
            <div className="p-2 bg-purple-500/20 rounded-xl">
              <ImageIcon className="w-6 h-6 text-purple-500" />
            </div>
            {lang === 'ar' ? 'مختبر تصميم الشعارات الذكي' : 'Smart Logo Design Lab'}
          </h2>
          <p className="text-zinc-400 mb-8 max-w-xl">
            {lang === 'ar' 
              ? 'حول رؤيتك إلى هوية بصرية احترافية في ثوانٍ معدودة باستخدام أقوى نماذج التوليد الصوري.' 
              : 'Transform your vision into a professional visual identity in seconds using the most powerful image generation models.'}
          </p>

          <div className="space-y-6">
            <div className="space-y-3">
              <label className="text-xs font-bold text-zinc-500 uppercase tracking-widest flex items-center gap-2">
                <Wand2 className="w-3 h-3" />
                {lang === 'ar' ? 'وصف الشعار (Logo Description)' : 'Logo Description'}
              </label>
              <textarea 
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder={lang === 'ar' ? 'مثال: شعار لشركة ذكاء اصطناعي، بسيط، ألوان زرقاء...' : 'e.g., Logo for an AI company, minimalist, blue colors...'}
                className="w-full bg-black border border-zinc-800 rounded-2xl p-5 text-white focus:outline-none focus:border-purple-500 transition-all min-h-[120px] resize-none"
              />
            </div>

            <div className="flex flex-wrap gap-2">
              {suggestions.map((s, i) => (
                <button
                  key={i}
                  onClick={() => setPrompt(s)}
                  className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-400 hover:text-white rounded-full text-[10px] font-bold uppercase transition-all"
                >
                  {s}
                </button>
              ))}
            </div>

            <button 
              onClick={handleGenerate} 
              disabled={isLoading || !prompt.trim()}
              className="w-full py-5 bg-purple-600 hover:bg-purple-500 disabled:opacity-50 text-white rounded-2xl font-black text-lg flex items-center justify-center gap-3 transition-all shadow-lg shadow-purple-600/20"
            >
              {isLoading ? (
                <>
                  <Loader2 className="w-6 h-6 animate-spin" />
                  {lang === 'ar' ? 'جاري التصميم...' : 'Designing...'}
                </>
              ) : (
                <>
                  <Sparkles className="w-6 h-6" />
                  {lang === 'ar' ? 'توليد الشعار الاحترافي' : 'Generate Professional Logo'}
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      <AnimatePresence>
        {result && (
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="p-8 bg-zinc-900 border border-zinc-800 rounded-[32px] flex flex-col items-center gap-8"
          >
            <div className="relative group">
              <div className="absolute -inset-4 bg-purple-500/20 blur-2xl rounded-full opacity-0 group-hover:opacity-100 transition-opacity" />
              <img 
                src={result} 
                alt="Generated Logo" 
                className="relative w-full max-w-md rounded-2xl shadow-2xl border border-zinc-800" 
              />
            </div>

            <div className="flex flex-col items-center gap-4 w-full max-w-md">
              <div className="flex items-center gap-2 text-zinc-500 text-[10px] font-mono uppercase tracking-widest">
                <RefreshCw className="w-3 h-3" />
                {lang === 'ar' ? 'تم التوليد بواسطة:' : 'Generated by:'} {modelUsed}
              </div>
              
              <div className="flex gap-4 w-full">
                <a 
                  href={result} 
                  download="logo.png"
                  className="flex-1 py-4 bg-zinc-800 hover:bg-zinc-700 text-white rounded-xl font-bold flex items-center justify-center gap-2 transition-all"
                >
                  <Download className="w-5 h-5" />
                  {lang === 'ar' ? 'تحميل الشعار' : 'Download Logo'}
                </a>
                <button 
                  onClick={handleGenerate}
                  className="px-6 py-4 border border-zinc-800 hover:bg-zinc-900 text-white rounded-xl transition-all"
                >
                  <RefreshCw className="w-5 h-5" />
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
