import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Music, Loader2, Headphones, Mic2, Radio } from 'lucide-react';
import { brandApi } from '../../api/brandApi';
import { toast } from 'sonner';

export const MusicLab: React.FC<{ lang: string }> = ({ lang }) => {
  const [prompt, setPrompt] = useState('');
  const [result, setResult] = useState<{ audio: string, mimeType: string } | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [availableModels, setAvailableModels] = useState<{ id: string, name: string }[]>([]);
  const [selectedModel, setSelectedModel] = useState<string>('');

  React.useEffect(() => {
    brandApi.getModels().then(models => {
      setAvailableModels(models);
      if (models.length > 0) setSelectedModel(models[0].name);
    }).catch(console.error);
  }, []);

  const musicPrompts = [
    "A cinematic orchestral track with high tension and dramatic strings",
    "Upbeat lo-fi hip hop with a relaxing jazz piano melody",
    "Futuristic synthwave with heavy bass and retro 80s vibes",
    "Traditional Arabic oud melody with modern electronic beats",
    "Calm acoustic guitar folk song for a peaceful morning",
    "High-energy techno track for a fast-paced workout",
    "Ambient space music with ethereal pads and distant echoes",
    "Classic 90s boom bap beat with a soulful vocal sample"
  ];

  const randomizePrompt = () => {
    const random = musicPrompts[Math.floor(Math.random() * musicPrompts.length)];
    setPrompt(random);
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    
    setIsLoading(true);
    setResult(null);
    setAudioUrl(null);
    try {
      const res = await brandApi.executeUniversal({
        prompt,
        taskType: "music",
        modelName: selectedModel
      });
      
      console.log("MusicLab: Received response:", res);
      
      // Check if response is valid and contains actual audio data
      if (!res || (!res.audio && !res.uri && !res.text)) {
        throw new Error("Model returned an empty or invalid response.");
      }

      setResult(res as any);
      const modelUsed = (res as any).modelUsed || selectedModel || "Smart Music Engine";
      
      if ((res as any).audio) {
        // Decode base64 audio into a playable Blob URL
        const base64 = (res as any).audio;
        
        // Remove data URL prefix if present
        const cleanBase64 = base64.includes(',') ? base64.split(',')[1] : base64;
        
        // Convert base64 to Uint8Array
        const response = await fetch(`data:application/octet-stream;base64,${cleanBase64}`);
        const blobData = await response.blob();
        
        if (blobData.size === 0) {
          throw new Error("Generated audio file is empty (0 bytes).");
        }
        
        const bytes = new Uint8Array(await blobData.arrayBuffer());
        
        const mimeType = (res as any).mimeType || 'audio/wav';
        console.log("MusicLab: Creating Blob with type:", mimeType, "and size:", bytes.length);
        
        const blob = new Blob([bytes], { type: mimeType });
        
        // If the blob is small enough, convert to Data URL to avoid range issues
        if (bytes.length < 10 * 1024 * 1024) { // 10MB
          const reader = new FileReader();
          reader.onloadend = () => {
            setAudioUrl(reader.result as string);
          };
          reader.readAsDataURL(blob);
        } else {
          // For larger files, create a blob URL and ensure it's revoked on cleanup
          const url = URL.createObjectURL(blob);
          setAudioUrl(url);
        }
      } else if (res.uri) {
        setAudioUrl(res.uri);
      } else if (res.text && (res.text.startsWith('http') || res.text.startsWith('data:audio'))) {
        setAudioUrl(res.text);
      } else {
        throw new Error("Could not extract a valid audio URL from the response.");
      }

      toast.success(lang === 'ar' ? `تم التوليد بواسطة ${modelUsed}` : `Generated by ${modelUsed}`);
    } catch (error: any) {
      const errorMsg = error.message || 'Failed to generate music';
      toast.error(lang === 'ar' ? `فشل توليد الموسيقى: ${errorMsg}` : `Failed to generate music: ${errorMsg}`);
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-8">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {[
          { icon: Headphones, label: lang === 'ar' ? 'نموذج التوليد' : 'Generation Model', value: (
            <select 
              value={selectedModel} 
              onChange={(e) => setSelectedModel(e.target.value)}
              className="bg-transparent text-white text-lg p-0 border-none outline-none w-full font-black cursor-pointer"
            >
              <option value="">{lang === 'ar' ? 'تلقائي (الأفضل)' : 'Auto (Best)'}</option>
              {availableModels.map(model => (
                <option key={model.id} value={model.name}>{model.name}</option>
              ))}
            </select>
          ), color: 'text-indigo-500' },
          { icon: Mic2, label: lang === 'ar' ? 'الجودة' : 'Quality', value: 'Lossless Audio', color: 'text-blue-500' },
          { icon: Radio, label: lang === 'ar' ? 'التردد' : 'Sample Rate', value: '48kHz', color: 'text-purple-500' },
        ].map((stat, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="p-6 bg-zinc-900 border border-zinc-800 rounded-3xl"
          >
            <stat.icon className={`w-6 h-6 ${stat.color} mb-4`} />
            <div className="text-2xl font-black">{stat.value}</div>
            <div className="text-xs text-zinc-500 uppercase tracking-widest">{stat.label}</div>
          </motion.div>
        ))}
      </div>

      <div className="p-8 bg-zinc-900 border border-zinc-800 rounded-[32px]">
        <h2 className="text-2xl font-black mb-6 flex items-center gap-2">
          <Music className="w-6 h-6 text-indigo-500" />
          {lang === 'ar' ? 'مختبر إنتاج الموسيقى' : 'Music Production Lab'}
        </h2>
        
        <div className="flex flex-col gap-4 mb-8">
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder={lang === 'ar' ? 'صف نوع الموسيقى، الآلات، والمزاج العام الذي تريده...' : 'Describe the music genre, instruments, and overall mood you want...'}
            className="w-full bg-black border border-zinc-800 rounded-xl px-4 py-4 text-white focus:outline-none focus:border-indigo-500 min-h-[120px] resize-none"
          />
          <div className="flex flex-wrap gap-4 justify-between items-center">
            <button
              onClick={randomizePrompt}
              className="px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
            >
              <Radio className="w-4 h-4" />
              {lang === 'ar' ? 'اقتراح نص عشوائي' : 'Randomize Prompt'}
            </button>
            <button
              onClick={handleGenerate}
              disabled={isLoading || !prompt.trim()}
              className="px-6 py-4 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white rounded-xl font-bold flex items-center justify-center gap-2 transition-colors w-full sm:w-auto"
            >
              {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Music className="w-5 h-5" />}
              {lang === 'ar' ? 'توليد المقطوعة الموسيقية' : 'Generate Music'}
            </button>
          </div>
        </div>

        {isLoading && (
          <div className="flex flex-col items-center justify-center py-12 text-zinc-500">
            <Loader2 className="w-12 h-12 animate-spin mb-4 text-indigo-500" />
            <p>{lang === 'ar' ? 'جاري توليد الموسيقى...' : 'Generating music...'}</p>
          </div>
        )}

        {audioUrl && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="p-6 bg-black/50 rounded-2xl border border-zinc-800/50 flex flex-col items-center gap-6"
          >
            <div className="text-xs text-zinc-500 font-mono break-all">
              Debug URL: {audioUrl.substring(0, 50)}...
            </div>
            <div className="w-full max-w-2xl bg-zinc-900 p-6 rounded-2xl border border-zinc-800 flex items-center gap-6">
              <div className="w-16 h-16 bg-indigo-500/20 rounded-full flex items-center justify-center shrink-0">
                <Music className="w-8 h-8 text-indigo-500" />
              </div>
              <div className="flex-1">
                <audio 
                  src={audioUrl} 
                  controls 
                  className="w-full"
                  onError={(e) => console.error("Audio playback error", e.type)}
                />
              </div>
            </div>
            
            <a 
              href={audioUrl} 
              download="generated-music.wav"
              className="px-6 py-3 bg-zinc-800 hover:bg-zinc-700 text-white rounded-xl font-bold transition-colors"
            >
              {lang === 'ar' ? 'تحميل المقطوعة' : 'Download Audio'}
            </a>
          </motion.div>
        )}
      </div>
    </div>
  );
};
