import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Play, Loader2, Film, Clapperboard, Video } from 'lucide-react';
import { brandApi } from '../../api/brandApi';
import { toast } from 'sonner';

export const VideoLab: React.FC<{ lang: string }> = ({ lang }) => {
  const [prompt, setPrompt] = useState('');
  const [result, setResult] = useState<{ uri: string, apiKey: string } | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [availableModels, setAvailableModels] = useState<{ id: string, name: string }[]>([]);
  const [selectedModel, setSelectedModel] = useState<string>('');

  React.useEffect(() => {
    brandApi.getModels().then(models => {
      setAvailableModels(models);
      if (models.length > 0) setSelectedModel(models[0].name);
    }).catch(console.error);
  }, []);

  const videoPrompts = [
    "A neon hologram of a cat driving a sports car at top speed through a futuristic city",
    "Cinematic drone shot of a misty mountain range at sunrise with a lone eagle soaring",
    "Close-up of a futuristic robot eye reflecting a vibrant digital world",
    "Cyberpunk street scene with neon lights reflecting in puddles during a light rain",
    "Epic space battle with massive starships and colorful laser beams",
    "A peaceful underwater scene with glowing jellyfish and coral reefs",
    "Time-lapse of a flower blooming in a magical forest with floating spores",
    "A high-speed chase through a desert canyon with futuristic hoverbikes"
  ];

  const randomizePrompt = () => {
    const random = videoPrompts[Math.floor(Math.random() * videoPrompts.length)];
    setPrompt(random);
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    
    setIsLoading(true);
    setResult(null);
    setVideoUrl(null);
    try {
      const res = await brandApi.generateVideo(prompt, selectedModel);
      console.log("VideoLab response:", res);
      
      const videoResult = res.video || res.uri || res.text;
      const modelUsed = res.modelUsed || selectedModel || "Smart Video Engine";

      if (videoResult && (typeof videoResult === 'string')) {
        setVideoUrl(videoResult);
        toast.success(lang === 'ar' ? `تم توليد الفيديو بواسطة ${modelUsed}` : `Video generated by ${modelUsed}`);
      } else {
        throw new Error(lang === 'ar' ? 'لم يتم استلام فيديو صالح' : 'No valid video received');
      }
    } catch (error: any) {
      const errorMsg = error.message || 'Failed to generate video';
      toast.error(lang === 'ar' ? `فشل توليد الفيديو: ${errorMsg}` : `Failed to generate video: ${errorMsg}`);
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-8">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {[
          { icon: Film, label: lang === 'ar' ? 'نموذج التوليد' : 'Generation Model', value: (
            <select 
              value={selectedModel} 
              onChange={(e) => setSelectedModel(e.target.value)}
              className="bg-transparent text-white text-lg p-0 border-none outline-none w-full font-black cursor-pointer"
            >
              <option value="">{lang === 'ar' ? 'تلقائي (الأفضل)' : 'Auto (Best)'}</option>
              {availableModels.map(model => (
                <option key={model.id} value={model.name}>{model.name}</option>
              ))}
            </select>
          ), color: 'text-pink-500' },
          { icon: Clapperboard, label: lang === 'ar' ? 'الجودة' : 'Quality', value: '720p Cinematic', color: 'text-purple-500' },
          { icon: Video, label: lang === 'ar' ? 'الإطارات' : 'FPS', value: '24fps', color: 'text-blue-500' },
        ].map((stat, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="p-6 bg-zinc-900 border border-zinc-800 rounded-3xl"
          >
            <stat.icon className={`w-6 h-6 ${stat.color} mb-4`} />
            <div className="text-2xl font-black">{stat.value}</div>
            <div className="text-xs text-zinc-500 uppercase tracking-widest">{stat.label}</div>
          </motion.div>
        ))}
      </div>

      <div className="p-8 bg-zinc-900 border border-zinc-800 rounded-[32px]">
        <h2 className="text-2xl font-black mb-6 flex items-center gap-2">
          <Play className="w-6 h-6 text-pink-500" />
          {lang === 'ar' ? 'مختبر إنتاج الفيديو' : 'Video Production Lab'}
        </h2>
        
        <div className="flex flex-col gap-4 mb-8">
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder={lang === 'ar' ? 'صف مشهد الفيديو الذي تتخيله بالتفصيل...' : 'Describe the video scene you imagine in detail...'}
            className="w-full bg-black border border-zinc-800 rounded-xl px-4 py-4 text-white focus:outline-none focus:border-pink-500 min-h-[120px] resize-none"
          />
          <div className="flex flex-wrap gap-4 justify-between items-center">
            <button
              onClick={randomizePrompt}
              className="px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
            >
              <Video className="w-4 h-4" />
              {lang === 'ar' ? 'اقتراح نص عشوائي' : 'Randomize Prompt'}
            </button>
            <button
              onClick={handleGenerate}
              disabled={isLoading || !prompt.trim()}
              className="px-6 py-4 bg-pink-600 hover:bg-pink-700 disabled:opacity-50 text-white rounded-xl font-bold flex items-center justify-center gap-2 transition-colors w-full sm:w-auto"
            >
              {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Play className="w-5 h-5" />}
              {lang === 'ar' ? 'توليد الفيديو' : 'Generate Video'}
            </button>
          </div>
        </div>

        {isLoading && (
          <div className="flex flex-col items-center justify-center py-12 text-zinc-500">
            <Loader2 className="w-12 h-12 animate-spin mb-4 text-pink-500" />
            <p>{lang === 'ar' ? 'جاري توليد الفيديو... قد يستغرق هذا بضع دقائق.' : 'Generating video... This may take a few minutes.'}</p>
          </div>
        )}

        {videoUrl && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="p-6 bg-black/50 rounded-2xl border border-zinc-800/50 flex flex-col items-center"
          >
            <div className="text-xs text-zinc-500 font-mono break-all mb-4">
              Debug URL: {videoUrl.substring(0, 50)}...
            </div>
            <video 
              src={videoUrl} 
              controls 
              autoPlay 
              muted
              playsInline
              loop 
              className="w-full max-w-3xl rounded-xl shadow-2xl border border-zinc-800"
              onError={(e) => console.error("Video playback error", e.type)}
            />
            <a 
              href={videoUrl} 
              download="generated-video.mp4"
              className="mt-6 px-6 py-3 bg-zinc-800 hover:bg-zinc-700 text-white rounded-xl font-bold transition-colors"
            >
              {lang === 'ar' ? 'تحميل الفيديو' : 'Download Video'}
            </a>
          </motion.div>
        )}
      </div>
    </div>
  );
};
